# Generated by Django 3.2.2 on 2021-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0002_alter_logger_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
