# Generated by Django 3.2.2 on 2021-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0003_alter_logger_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
